#!/usr/bin/perl

#
# core_estimator.pl
# Autogenerated by gpsketcher
# Generated on Fri Jul 22 01:44:14 2016
#

#
# Class: 
#

use strict;
use warnings;
use Glib qw( TRUE FALSE );
use Gtk2 '-init';


package Estimate;

use Gtk2::GladeXML::Simple;

use base qw( Gtk2::GladeXML::Simple );

our ( $VERSION, $APPNAME ) = ( '0.1', 'core_estimator' );

sub new {
    my ( $class ) = @_;
    my $self = $class->SUPER::new( 'core_estimator.glade', '', 'core_estimator' );

    print "A new  object has been created\n";

    return $self;
}

#
# Write your own methods here
# ...
#

1;

#
# main
#
package main;

my $builder=Gtk2::Builder->new;

my $app="core_estimator.xml";

$builder->add_from_file($app);

#my $app = Estimate->new();
die "Got here\n";
$app->run();

1;

